name: Run CMake for Dragon

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux-unix-makefiles:
    name: Run Dragon Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: run action
        id: run_action
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.DRAGON_ACTION_CMAKE_EDIT_SUBMODULE_EDIT }}
          parent_repository: KhrySystem/Dragon
          checkout_branch: main
          pr_against_branch: main
          owner: KhrySystem